services:
  postgres:
    image: postgres:17
    container_name: codelens-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: codelens

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:latest
    container_name: codelens-qdrant

    restart: unless-stopped

    ports:
      - "6333:6333"

    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  postgres_data:
  qdrant_data: